"use strict";
window.addEventListener('load', (_event) => { console.log("has loaded"); });
const canvas = document.querySelector("canvas");
const crc2 = canvas.getContext("2d");
crc2.fillStyle = "#201787ff";
crc2.fillRect(0, 0, crc2.canvas.width, crc2.canvas.height);
crc2.beginPath();
crc2.arc(crc2.canvas.width / 2, crc2.canvas.height / 2, 90, 0, 10);
crc2.closePath();
crc2.stroke();
const path = new Path2D();
// path.moveTo(crc2.canvas.width / 2, crc2.canvas.height / 2);
crc2.beginPath();
crc2.lineTo(crc2.canvas.width / 2, crc2.canvas.height / 2);
crc2.lineTo(crc2.canvas.width / 2 + 90, crc2.canvas.height / 2);
crc2.closePath();
crc2.stroke();
console.log("AAAAAAAAaaa");
